/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Charge {
  'projectType' : ProjectType,
  'description' : string,
  'amount' : bigint,
}
export type ProjectType = { 'graduation_pdf_binding' : null } |
  { 'graduation_pdf_only' : null } |
  { 'tenth_twelfth_handwritten' : null };
export interface StatusEntry {
  'status' : SubmissionStatus,
  'timestamp' : Timestamp,
}
export type SubmissionId = bigint;
export interface SubmissionPublic {
  'id' : SubmissionId,
  'studentName' : string,
  'projectType' : ProjectType,
  'classCourse' : string,
  'studentPrincipal' : UserId,
  'submittedAt' : Timestamp,
  'statusHistory' : Array<StatusEntry>,
  'teacherName' : string,
  'rollNumber' : string,
  'principalName' : string,
  'adminNotes' : string,
  'currentStatus' : SubmissionStatus,
  'enrollmentNumber' : string,
}
export type SubmissionStatus = { 'submitted' : null } |
  { 'in_progress' : null } |
  { 'completed' : null } |
  { 'ready_for_pickup' : null };
export interface SubmitRequest {
  'studentName' : string,
  'projectType' : ProjectType,
  'classCourse' : string,
  'teacherName' : string,
  'rollNumber' : string,
  'principalName' : string,
  'enrollmentNumber' : string,
}
export type Timestamp = bigint;
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllSubmissions' : ActorMethod<[], Array<SubmissionPublic>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCharges' : ActorMethod<[], Array<Charge>>,
  'getMySubmission' : ActorMethod<[SubmissionId], [] | [SubmissionPublic]>,
  'getMySubmissions' : ActorMethod<[], Array<SubmissionPublic>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitProject' : ActorMethod<[SubmitRequest], SubmissionId>,
  'updateAdminNotes' : ActorMethod<[SubmissionId, string], undefined>,
  'updateSubmissionStatus' : ActorMethod<
    [SubmissionId, SubmissionStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];