/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SubmissionId = IDL.Nat;
export const ProjectType = IDL.Variant({
  'graduation_pdf_binding' : IDL.Null,
  'graduation_pdf_only' : IDL.Null,
  'tenth_twelfth_handwritten' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const SubmissionStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'in_progress' : IDL.Null,
  'completed' : IDL.Null,
  'ready_for_pickup' : IDL.Null,
});
export const StatusEntry = IDL.Record({
  'status' : SubmissionStatus,
  'timestamp' : Timestamp,
});
export const SubmissionPublic = IDL.Record({
  'id' : SubmissionId,
  'studentName' : IDL.Text,
  'projectType' : ProjectType,
  'classCourse' : IDL.Text,
  'studentPrincipal' : UserId,
  'submittedAt' : Timestamp,
  'statusHistory' : IDL.Vec(StatusEntry),
  'teacherName' : IDL.Text,
  'rollNumber' : IDL.Text,
  'principalName' : IDL.Text,
  'adminNotes' : IDL.Text,
  'currentStatus' : SubmissionStatus,
  'enrollmentNumber' : IDL.Text,
});
export const Charge = IDL.Record({
  'projectType' : ProjectType,
  'description' : IDL.Text,
  'amount' : IDL.Nat,
});
export const SubmitRequest = IDL.Record({
  'studentName' : IDL.Text,
  'projectType' : ProjectType,
  'classCourse' : IDL.Text,
  'teacherName' : IDL.Text,
  'rollNumber' : IDL.Text,
  'principalName' : IDL.Text,
  'enrollmentNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(SubmissionPublic)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharges' : IDL.Func([], [IDL.Vec(Charge)], ['query']),
  'getMySubmission' : IDL.Func(
      [SubmissionId],
      [IDL.Opt(SubmissionPublic)],
      ['query'],
    ),
  'getMySubmissions' : IDL.Func([], [IDL.Vec(SubmissionPublic)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitProject' : IDL.Func([SubmitRequest], [SubmissionId], []),
  'updateAdminNotes' : IDL.Func([SubmissionId, IDL.Text], [], []),
  'updateSubmissionStatus' : IDL.Func([SubmissionId, SubmissionStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SubmissionId = IDL.Nat;
  const ProjectType = IDL.Variant({
    'graduation_pdf_binding' : IDL.Null,
    'graduation_pdf_only' : IDL.Null,
    'tenth_twelfth_handwritten' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const SubmissionStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'in_progress' : IDL.Null,
    'completed' : IDL.Null,
    'ready_for_pickup' : IDL.Null,
  });
  const StatusEntry = IDL.Record({
    'status' : SubmissionStatus,
    'timestamp' : Timestamp,
  });
  const SubmissionPublic = IDL.Record({
    'id' : SubmissionId,
    'studentName' : IDL.Text,
    'projectType' : ProjectType,
    'classCourse' : IDL.Text,
    'studentPrincipal' : UserId,
    'submittedAt' : Timestamp,
    'statusHistory' : IDL.Vec(StatusEntry),
    'teacherName' : IDL.Text,
    'rollNumber' : IDL.Text,
    'principalName' : IDL.Text,
    'adminNotes' : IDL.Text,
    'currentStatus' : SubmissionStatus,
    'enrollmentNumber' : IDL.Text,
  });
  const Charge = IDL.Record({
    'projectType' : ProjectType,
    'description' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const SubmitRequest = IDL.Record({
    'studentName' : IDL.Text,
    'projectType' : ProjectType,
    'classCourse' : IDL.Text,
    'teacherName' : IDL.Text,
    'rollNumber' : IDL.Text,
    'principalName' : IDL.Text,
    'enrollmentNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(SubmissionPublic)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharges' : IDL.Func([], [IDL.Vec(Charge)], ['query']),
    'getMySubmission' : IDL.Func(
        [SubmissionId],
        [IDL.Opt(SubmissionPublic)],
        ['query'],
      ),
    'getMySubmissions' : IDL.Func([], [IDL.Vec(SubmissionPublic)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitProject' : IDL.Func([SubmitRequest], [SubmissionId], []),
    'updateAdminNotes' : IDL.Func([SubmissionId, IDL.Text], [], []),
    'updateSubmissionStatus' : IDL.Func(
        [SubmissionId, SubmissionStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };