/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface SubmitRequest {
    studentName: string;
    projectType: ProjectType;
    classCourse: string;
    teacherName: string;
    rollNumber: string;
    principalName: string;
    enrollmentNumber: string;
}
export interface StatusEntry {
    status: SubmissionStatus;
    timestamp: Timestamp;
}
export interface SubmissionPublic {
    id: SubmissionId;
    studentName: string;
    projectType: ProjectType;
    classCourse: string;
    studentPrincipal: UserId;
    submittedAt: Timestamp;
    statusHistory: Array<StatusEntry>;
    teacherName: string;
    rollNumber: string;
    principalName: string;
    adminNotes: string;
    currentStatus: SubmissionStatus;
    enrollmentNumber: string;
}
export interface Charge {
    projectType: ProjectType;
    description: string;
    amount: bigint;
}
export type SubmissionId = bigint;
export enum ProjectType {
    graduation_pdf_binding = "graduation_pdf_binding",
    graduation_pdf_only = "graduation_pdf_only",
    tenth_twelfth_handwritten = "tenth_twelfth_handwritten"
}
export enum SubmissionStatus {
    submitted = "submitted",
    in_progress = "in_progress",
    completed = "completed",
    ready_for_pickup = "ready_for_pickup"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllSubmissions(): Promise<Array<SubmissionPublic>>;
    getCallerUserRole(): Promise<UserRole>;
    getCharges(): Promise<Array<Charge>>;
    getMySubmission(id: SubmissionId): Promise<SubmissionPublic | null>;
    getMySubmissions(): Promise<Array<SubmissionPublic>>;
    isCallerAdmin(): Promise<boolean>;
    submitProject(req: SubmitRequest): Promise<SubmissionId>;
    updateAdminNotes(id: SubmissionId, notes: string): Promise<void>;
    updateSubmissionStatus(id: SubmissionId, newStatus: SubmissionStatus): Promise<void>;
}
import type { Charge as _Charge, ProjectType as _ProjectType, StatusEntry as _StatusEntry, SubmissionId as _SubmissionId, SubmissionPublic as _SubmissionPublic, SubmissionStatus as _SubmissionStatus, SubmitRequest as _SubmitRequest, Timestamp as _Timestamp, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllSubmissions(): Promise<Array<SubmissionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCharges(): Promise<Array<Charge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCharges();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCharges();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubmission(arg0: SubmissionId): Promise<SubmissionPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubmission(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubmission(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubmissions(): Promise<Array<SubmissionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubmissions();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubmissions();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async submitProject(arg0: SubmitRequest): Promise<SubmissionId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitProject(to_candid_SubmitRequest_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitProject(to_candid_SubmitRequest_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAdminNotes(arg0: SubmissionId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminNotes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminNotes(arg0, arg1);
            return result;
        }
    }
    async updateSubmissionStatus(arg0: SubmissionId, arg1: SubmissionStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubmissionStatus(arg0, to_candid_SubmissionStatus_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubmissionStatus(arg0, to_candid_SubmissionStatus_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Charge_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Charge): Charge {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectType): ProjectType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_StatusEntry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusEntry): StatusEntry {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionPublic_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionPublic): SubmissionPublic {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionStatus): SubmissionStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubmissionPublic]): SubmissionPublic | null {
    return value.length === 0 ? null : from_candid_SubmissionPublic_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SubmissionStatus;
    timestamp: _Timestamp;
}): {
    status: SubmissionStatus;
    timestamp: Timestamp;
} {
    return {
        status: from_candid_SubmissionStatus_n11(_uploadFile, _downloadFile, value.status),
        timestamp: value.timestamp
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    projectType: _ProjectType;
    description: string;
    amount: bigint;
}): {
    projectType: ProjectType;
    description: string;
    amount: bigint;
} {
    return {
        projectType: from_candid_ProjectType_n6(_uploadFile, _downloadFile, value.projectType),
        description: value.description,
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SubmissionId;
    studentName: string;
    projectType: _ProjectType;
    classCourse: string;
    studentPrincipal: _UserId;
    submittedAt: _Timestamp;
    statusHistory: Array<_StatusEntry>;
    teacherName: string;
    rollNumber: string;
    principalName: string;
    adminNotes: string;
    currentStatus: _SubmissionStatus;
    enrollmentNumber: string;
}): {
    id: SubmissionId;
    studentName: string;
    projectType: ProjectType;
    classCourse: string;
    studentPrincipal: UserId;
    submittedAt: Timestamp;
    statusHistory: Array<StatusEntry>;
    teacherName: string;
    rollNumber: string;
    principalName: string;
    adminNotes: string;
    currentStatus: SubmissionStatus;
    enrollmentNumber: string;
} {
    return {
        id: value.id,
        studentName: value.studentName,
        projectType: from_candid_ProjectType_n6(_uploadFile, _downloadFile, value.projectType),
        classCourse: value.classCourse,
        studentPrincipal: value.studentPrincipal,
        submittedAt: value.submittedAt,
        statusHistory: from_candid_vec_n8(_uploadFile, _downloadFile, value.statusHistory),
        teacherName: value.teacherName,
        rollNumber: value.rollNumber,
        principalName: value.principalName,
        adminNotes: value.adminNotes,
        currentStatus: from_candid_SubmissionStatus_n11(_uploadFile, _downloadFile, value.currentStatus),
        enrollmentNumber: value.enrollmentNumber
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    in_progress: null;
} | {
    completed: null;
} | {
    ready_for_pickup: null;
}): SubmissionStatus {
    return "submitted" in value ? SubmissionStatus.submitted : "in_progress" in value ? SubmissionStatus.in_progress : "completed" in value ? SubmissionStatus.completed : "ready_for_pickup" in value ? SubmissionStatus.ready_for_pickup : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    graduation_pdf_binding: null;
} | {
    graduation_pdf_only: null;
} | {
    tenth_twelfth_handwritten: null;
}): ProjectType {
    return "graduation_pdf_binding" in value ? ProjectType.graduation_pdf_binding : "graduation_pdf_only" in value ? ProjectType.graduation_pdf_only : "tenth_twelfth_handwritten" in value ? ProjectType.tenth_twelfth_handwritten : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Charge>): Array<Charge> {
    return value.map((x)=>from_candid_Charge_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubmissionPublic>): Array<SubmissionPublic> {
    return value.map((x)=>from_candid_SubmissionPublic_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StatusEntry>): Array<StatusEntry> {
    return value.map((x)=>from_candid_StatusEntry_n9(_uploadFile, _downloadFile, x));
}
function to_candid_ProjectType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectType): _ProjectType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_SubmissionStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionStatus): _SubmissionStatus {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_SubmitRequest_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitRequest): _SubmitRequest {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentName: string;
    projectType: ProjectType;
    classCourse: string;
    teacherName: string;
    rollNumber: string;
    principalName: string;
    enrollmentNumber: string;
}): {
    studentName: string;
    projectType: _ProjectType;
    classCourse: string;
    teacherName: string;
    rollNumber: string;
    principalName: string;
    enrollmentNumber: string;
} {
    return {
        studentName: value.studentName,
        projectType: to_candid_ProjectType_n21(_uploadFile, _downloadFile, value.projectType),
        classCourse: value.classCourse,
        teacherName: value.teacherName,
        rollNumber: value.rollNumber,
        principalName: value.principalName,
        enrollmentNumber: value.enrollmentNumber
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectType): {
    graduation_pdf_binding: null;
} | {
    graduation_pdf_only: null;
} | {
    tenth_twelfth_handwritten: null;
} {
    return value == ProjectType.graduation_pdf_binding ? {
        graduation_pdf_binding: null
    } : value == ProjectType.graduation_pdf_only ? {
        graduation_pdf_only: null
    } : value == ProjectType.tenth_twelfth_handwritten ? {
        tenth_twelfth_handwritten: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionStatus): {
    submitted: null;
} | {
    in_progress: null;
} | {
    completed: null;
} | {
    ready_for_pickup: null;
} {
    return value == SubmissionStatus.submitted ? {
        submitted: null
    } : value == SubmissionStatus.in_progress ? {
        in_progress: null
    } : value == SubmissionStatus.completed ? {
        completed: null
    } : value == SubmissionStatus.ready_for_pickup ? {
        ready_for_pickup: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
